Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,13 +1,15 @@
 name: CICD
+
 on:
   push:
     branches:
       - main
     tags:
       - 'v*'
+
 env:
   IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/static-nginx-app
-  RELEASE_NAME: static-nginx-app
+  RELEASE_NAME: myapp
   NAMESPACE: monitoring
 
 jobs:
@@ -15,8 +17,9 @@ jobs:
     name: Build Docker image
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
+      - name: Checkout code
         uses: actions/checkout@v4
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -26,15 +29,21 @@ jobs:
       - name: Setup Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      - name: Extract version from commit messages
+      - name: Extract version from tag or commit message
         run: |
-          VERSION=$(git log -1 --pretty=format:%B)
-          if [[ ! -z "$VERSION" ]]; then
-            echo "VERSION=$VERSION" >> $GITHUB_ENV
+          echo "GITHUB_REF: ${GITHUB_REF}"
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            VERSION=${GITHUB_REF#refs/tags/}
           else
-            echo "No version found in the commit message"
+            VERSION=$(git log -1 --pretty=format:%B | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' || echo "")
+          fi
+          if [[ -z "$VERSION" ]]; then
+            echo "No version found in the commit message or tag"
             exit 1
           fi
+          VERSION=${VERSION//[[:space:]]/}  # Remove any spaces
+          echo "Using version: $VERSION"
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV
 
       - name: Build and push
         uses: docker/build-push-action@v5
@@ -43,47 +52,65 @@ jobs:
           file: ./Dockerfile
           push: true
           tags: ${{ env.IMAGE_TAG }}:${{ env.VERSION }}
-
+  
   deploy:
     needs: build-and-push
     name: Deploy to Kubernetes
-    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v')
     runs-on: ubuntu-latest
+    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v')
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
+
+      - name: List files in the working directory
+        run: |
+          ls -la
 
       - name: Set up Kubernetes
-        uses: azure/setup-kubectl@v1
+        uses: azure/setup-kubectl@v3
         with:
           version: 'v1.21.0'
 
-      - name: Extract version from commit messages
+      - name: Extract version from tag or commit message
         run: |
-          VERSION=$(git log -1 --pretty=format:%B)
-          if [[ ! -z "$VERSION" ]]; then
-            echo "VERSION=$VERSION" >> $GITHUB_ENV
+          echo "GITHUB_REF: ${GITHUB_REF}"
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            VERSION=${GITHUB_REF#refs/tags/}
           else
-            echo "No version found in the commit message"
+            VERSION=$(git log -1 --pretty=format:%B | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' || echo "")
+          fi
+          if [[ -z "$VERSION" ]]; then
+            echo "No version found in the commit message or tag"
             exit 1
           fi
+          VERSION=${VERSION//[[:space:]]/}  # Remove any spaces
+          echo "Using version: $VERSION"
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV
 
-      - name: Replace image tag in nginx-static-app.yaml
-        if: env.DEPLOY == 'false'
-       
+      - name: Replace image tag in deployment.yaml
         run: |
-          sed -i "s|image: littlelucidlynx/nginx-static-app:.*|image: ${{ env.IMAGE_TAG }}|" ./nginx-static-app.yaml
-        env:
-          IMAGE_TAG: littlelucidlynx/nginx-static-app:${{ env.VERSION }}
-      
+          if [ ! -f ./nginx-static-app.yaml ]; then
+            echo "nginx-static-app.yaml not found in the current directory"
+            exit 1
+          fi
+          sed -i "s|image: littlelucidlynx/nginx-static-app:.*|image: ${{ env.IMAGE_TAG }}:${{ env.VERSION }}|" ./nginx-static-app.yaml
+
       - name: Create kubeconfig
         run: |
           mkdir -p $HOME/.kube/
+
       - name: Authenticate to Kubernetes cluster
         env:
           KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
         run: |
-          echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 --decode > ${HOME}/.kube/config
+          echo "${KUBE_CONFIG_DATA}" | base64 --decode > ${HOME}/.kube/config
+          kubectl config view
+          kubectl get nodes
+
       - name: Apply Kubernetes manifests
         run: |
-          kubectl apply -f ./nginx-static-app.yaml 
+          kubectl apply -f ./nginx-static-app.yaml
+          kubectl get daemonsets -n monitoring
+          kubectl get pods -n monitoring
+          kubectl describe daemonset myapp -n monitoring
+          kubectl describe service myappsvc -n monitoring
